---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: core-cluster
stringData:
  .dockerconfigjson: '{"auths":{"quay-registry-quay-openshift-quay.apps.mano-307.ebc5.bos2.lab":{"auth":"cXVheWFkbWluOnF1YXlwYXNzMTIz","email":"jhendrix@karmalabs.com"}}}'
  type: kubernetes.io/dockerconfigjson
