apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common-49"
  namespace: "ztp-common-policies"
spec:
  bindingRules:
    common: "4.9"
  remediationAction: enforce
  sourceFiles:
    - fileName: OperatorHub.yaml
      policyName: "disconnected-olm"
      
    - fileName: DefaultCatsrc.yaml
      policyName: "disconnected-olm"
      metadata:
        name: redhat-operators
      spec:
        image: 192-168-37-122.sslip.io:5000/redhat/redhat-operator-index:v4.9
        sourceType: grpc
        displayName: Red Hat Operators
    - fileName: DefaultCatsrc.yaml
      policyName: "disconnected-olm"
      metadata:
        name: certified-operators
      spec:
        image: 192-168-37-122.sslip.io:5000/redhat/certified-operator-index:v4.9
        sourceType: grpc
        displayName: Certified Operators
    # PAO 
    - fileName: PaoSubscription.yaml
      policyName: "pao-sub-policy"
      spec:
        source: redhat-operators
        channel: "4.9"
    - fileName: PaoSubscriptionNS.yaml
      policyName: "pao-sub-policy"
    - fileName: PaoSubscriptionOperGroup.yaml
      policyName: "pao-sub-policy"
    # SRIOV
    - fileName: SriovSubscription.yaml
      policyName: "subscriptions-policy"
      spec:
        channel: "4.9"
    - fileName: SriovSubscriptionNS.yaml
      policyName: "subscriptions-policy"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "subscriptions-policy"
    #PTP
    - fileName: PtpSubscription.yaml
      policyName: "subscriptions-policy"
      spec:
        channel: "4.9"
    - fileName: PtpSubscriptionNS.yaml
      policyName: "subscriptions-policy"
    - fileName: PtpSubscriptionOperGroup.yaml
      policyName: "subscriptions-policy"
    #CLO
    - fileName: ClusterLogSubscription.yaml
      policyName: "subscriptions-policy"
    - fileName: ClusterLogNS.yaml
      policyName: "subscriptions-policy"
    - fileName: ClusterLogOperGroup.yaml
      policyName: "subscriptions-policy"
    #LSO
    - fileName: StorageNS.yaml
      policyName: "subscriptions-policy"
    - fileName: StorageOperGroup.yaml
      policyName: "subscriptions-policy"
    - fileName: StorageSubscription.yaml
      policyName: "subscriptions-policy"
      spec:
        channel: "4.9"
    # Reduce monitoring operator footprint
    - fileName: ReduceMonitoringFootprint.yaml
      policyName: "config-policy"



