---
apiVersion: v1
kind: Secret
metadata:
  name: core-master-0
  namespace: core-cluster
data:
  username: "YWRtaW4="
  password: "cmVkaGF0MTIz"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: core-master-1
  namespace: core-cluster
data:
  username: "YWRtaW4="
  password: "cmVkaGF0MTIz"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: core-master-2
  namespace: core-cluster
data:
  username: "YWRtaW4="
  password: "cmVkaGF0MTIz"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: core-worker-0
  namespace: core-cluster
data:
  username: "YWRtaW4="
  password: "cmVkaGF0MTIz"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: core-worker-1
  namespace: core-cluster
data:
  username: "YWRtaW4="
  password: "cmVkaGF0MTIz"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: core-worker-2
  namespace: core-cluster
data:
  username: "YWRtaW4="
  password: "cmVkaGF0MTIz"
type: Opaque
