apiVersion: v1
kind: Secret
metadata:
  name: config-bundle-secret
  namespace: openshift-quay
data:
  config.yaml: RkVBVFVSRV9VU0VSX0lOSVRJQUxJWkU6IHRydWUKQlJPV1NFUl9BUElfQ0FMTFNfWEhSX09OTFk6IGZhbHNlClNVUEVSX1VTRVJTOgotIHF1YXlhZG1pbgpGRUFUVVJFX1VTRVJfQ1JFQVRJT046IGZhbHNlCkNSRUFURV9OQU1FU1BBQ0VfT05fUFVTSDogdHJ1ZQo=
# FEATURE_USER_INITIALIZE: true
# BROWSER_API_CALLS_XHR_ONLY: false
# SUPER_USERS:
# - quayadmin
# FEATURE_USER_CREATION: false
# CREATE_NAMESPACE_ON_PUSH: true
